site_name: ZhiGrove
theme:
  name: material
  language: zh
  features:
    - navigation.sections
    - navigation.tracking
    # - navigation.indexes    # 让每个目录的 index.md 作为该目录的落地页
    # - toc.integrate
plugins:
  - search
docs_dir: docs
markdown_extensions:
  - meta